[theme]
primaryColor = "#228B22"
backgroundColor = "#0A1A2F"
secondaryBackgroundColor = "#2D3748"
textColor = "#F7FAFC"
font = "sans serif"

[client]
showErrorDetails = true
toolbarMode = "minimal"

[logger]
level = "warning"

[server]
runOnSave = true

